server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
        - id: u-carro-service
          uri: lb://u-carro-service
          predicates:
            - Path=/carro/**
        - id: u-moto-service
          uri: lb://u-moto-service
          predicates:
            - Path=/moto/**